anisahhoque/c15-court-transcript-pipeline

.github/workflows/pylint.yml, .github/workflows/pytest.yml, .gitignore, requirements.txt
This pull request introduces Continuous Integration and Continuous Deployment (CI/CD) pipelines to our repository using GitHub Actions. The CI/CD pipelines are configured to automatically run tests and check code quality when a pull request is created or when code is pushed to the repository.
=> Create CI/CD setup

dev-resources/quality-guide.md, dev-resources/style-guide.md
This pull requests creates files that explain the code quality guidelines and also style guidelines for the code that will be written for this project.
=> Created code quality and style guide files.

dev-resources/issue-template.md
Adds an inital issue template for use by developers and project manager when opening tickets
Closes #31
=> Adds an initial issue template for future use

cloud-resources/main.tf, cloud-resources/variables.tf
Adds terraform for database and subnet groups to support database
Closes #20
=> Adds database script, and associated resources

cloud-resources/main.tf
Adds two public subnets, a route table, and a internet gateway to support future public resources
Closes #63
=> Adds public subnet to VPC

schema/schema.sql
This pull requests uploads the schema for the DB.
=> Schema creation

streamlit/data_source.py, streamlit/pages/judgment_search.py, streamlit/test_datasource.py
This pull request creates the front end for judgment search page, while also testing every part of the code.
=> Streamlit Judgment Search

streamlit/data_source.py, streamlit/test_datasource.py
This pull request shows a short overview for a case.
=> Finished overview

cloud-resources/network-resources.tf, cloud-resources/server.tf
Terraforms ec2 in private subnet with s3 access 
Closes #92
=> Terraform ec2

streamlit/data_source.py, streamlit/test_datasource.py
This pull request adds more information on the summary page.
=> Adds parties involved to the judgment summary page.

streamlit/data_source.py, streamlit/test_datasource.py
This pull requests adds the new schema and ERD to the queries. It also adds summary to each judgment.
=> Adapted Script to New Schema and ERD

cloud-resources/Dockerfile, cloud-resources/pipeline-task.tf
- Removes Dockerfile
- Seeds pipeline ECR using public hello-world image
Closes #127
=> Removes dockerfile, and seeds pipeline with pulled hello-world

cloud-resources/README.md, cloud-resources/outputs.tf, cloud-resources/pipeline-task.tf, cloud-resources/variables.tf
Adds README to `cloud-resources`
Closes #129
=> Cloud readme

cloud-resources/README.md, cloud-resources/outputs.tf, cloud-resources/seeding-task.tf
Terraforms a task definition for the historical pipeline
Closes #131
=> Seed task def

seed_data/extract.py, seed_data/load.py
Quick fix to historical pipeline.
=> some simple fixes to pipeline

daily_pipeline/daily_extract.py, daily_pipeline/daily_load.py, daily_pipeline/daily_parse_xml.py, daily_pipeline/daily_pipeline.py, daily_pipeline/daily_prompt_engineering.py, daily_pipeline/daily_transform.py, daily_pipeline/requirements.txt, daily_pipeline/test.sh, daily_pipeline/test_daily_extract.py, daily_pipeline/test_daily_load.py, daily_pipeline/test_daily_parse_xml.py, daily_pipeline/test_daily_prompt_engineering.py
I created a new folder called daily_pipeline, with all the files for the daily version of the pipeline. It has very minor changes compared to the historical pipeline, and so most of the code was reused accordingly.
Closes #142
=> Completed pipeline for daily uploading

daily_pipeline/Dockerfile, seed_data/Dockerfile
Added dockerfiles for both pipelines, both tested and functioning properly.
Closes #144
=> Completed dockerfiles for both pipelines

.github/workflows/deploy-pipeline.yml
Provisionally completes autodeploy daily pipeline
Closes #147
=> completes autodeploy of daily pipeline

cloud-resources/outputs.tf, deploy-daily-pipeline.sh
Creates bash script which deploys the daily pipeline to ECR
Closes #133
=> Creates daily pipeline deployment script

daily_pipeline/daily_pipeline.py, seed_data/initial_seeding.py
Change pipeline scripts environment variables to be consistent with terraform environment variables.
=> Change pipeline scripts environment variables

deploy-historical-pipeline.sh, seed_data/Dockerfile
Creates a bash script which deploys the image to seed the database
Closes #132
=> Bash historical data

deploy-daily-pipeline.sh
Fixes breaking bug in bash script
Closes #133
=> Fixes environment variable naming bug

.github/workflows/deploy-pipeline.yml, .github/workflows/deploy-server.yml
Fixed auto-deploy to amd instead of arm
Closes #162
=> fixed auto-deploy platform types

.github/workflows/deploy-pipeline.yml, .github/workflows/deploy-server.yml
This should actually work properly now.
=> further fixes

README.md
Adds instructions on how to use deployment scripts to the root readme
Closes #164
=> Modifies the README to include instructions on how to use deploy scripts

.github/workflows/deploy-server.yml, deploy-server.sh
Fixes an aws bug in the deployment script
Closes #167
=> Fixes server deployment bug

cloud-resources/server-compute.tf, cloud-resources/server-service.tf, cloud-resources/server-task.tf
Modifies the terraform to host the server on an EC2 instance to reduce running costs
Closes #93 
Closes #170
=> Modifies terraform to run ECS service on an EC2

.github/workflows/pytest.yml, ses_lambda/Dockerfile, ses_lambda/requirements.txt, ses_lambda/ses_lambda.py, ses_lambda/test_ses_lambda.py
Created folder with appropriate files for SES Lambda, including main python file, test file and Dockerfile.
Closes #177 .
=> Folder containing everything needed for SES Lambda

deploy-ses-lambda.sh
Note that I haven't added a workflow file because the secrets may not yet be configured for the lambda ECR currently.
Closes #181 .
=> Added bash script for deploying SES lambda

streamlit/pages/subscribe.py, streamlit/subscribe_functions.py, streamlit/test_subscribe_functions.py
Created simple page where someone can enter their email and subscribe to daily emails containing information and links to previous day's judgments.
Closes #178 .
=> Added subscribe page to streamlit

streamlit/data_source.py
This will be needed for the SES email hyperlinks to work.
Closes #185 .
=> Made it so that individual judgment overviews are linkable

cloud-resources/email.tf, cloud-resources/outputs.tf, cloud-resources/pipeline-task.tf, cloud-resources/server-image.tf, cloud-resources/server-task.tf, cloud-resources/variables.tf
Creates initial email resources via terraform
Closes #172
=> Creates intial email resources

cloud-resources/pipeline-task.tf, cloud-resources/s3.tf, cloud-resources/seeding-task.tf, cloud-resources/server-task.tf
Updates name of S3 bucket to `judgment-html`
Closes #193
=> Updates s3 bucket name to reflect storage of new file type

streamlit/pages/subscribe.py
=> quick fix to subscribe page

streamlit/data_source.py, streamlit/pages/Explore_Judgments.py
It allows for switching between Judgment overview and full judgment text.
Closes #196 .
=> Added button to Explore_Judgments for option of viewing full judgment

cloud-resources/pipeline-task.tf, cloud-resources/s3.tf, cloud-resources/seeding-task.tf, cloud-resources/server-compute.tf, cloud-resources/server-service.tf, cloud-resources/server-task.tf
Gives more resources to the server infrastructure to support it
Closes #198
=> Expand server ec2

streamlit/requirements.txt
=> my bad on this one

streamlit/Dockerfile
=> added subscribe_functions to Dockerfile

ses_lambda/requirements.txt, streamlit/pages/subscribe.py, streamlit/subscribe_functions.py, streamlit/test_subscribe_functions.py
Turns out sesv2 needs region, who knew?
Also added some error handling for if someone is already subscribed
=> added region to subscribe function

ses_lambda/ses_lambda.py, ses_lambda/test_ses_lambda.py
Such annoying bugs, especially with fetching emails. Fixed now by specify region_name among other things.
Closes #209 .
=> fixed email ses lambda

.github/workflows/deploy-ses-lambda.yml
Added workflow file that auto-deploy the lambda image and updates lambda to use the newly deployed image.
Fixes #216 .
=> Added auto-deploy and auto-rerun for lambda image

streamlit/style.css
Red was not the best choice, a dark blue/gray looks nicer.
Closes #218 .
=> changed text colour to dark blue/gray

seed_data/prompt_engineering.py
This ensures that role always singular and more consistent.
Closes #222  .
=> Fixed role prompt engineering 

daily_pipeline/test_daily_load.py, daily_pipeline/test_daily_parse_xml.py, streamlit/test_components.py, streamlit/test_dashboard_functions.py, streamlit/test_datasource.py
This pull requests removes comments from tests and duplicate imports.
Closes #230 .
=> Clean duplicates imports in tests modules and functions.

streamlit/data_source.py
Now judgment case overview can be linked to directly.
Closes #232 .
=> Added anchor link to case overview
